---
- hosts: proxmox-server
  become: true
  tasks:
    - name: Update all packages
      apt:
        update_cache: yes

    - name: Install NFS server package
      apt: 
        name: nfs-kernel-server
        state: present

    - name: Create a directory to share
      file:
        path: /mnt/pve/hdd-sda/nfs-shares/k8s-pvs
        state: directory
        mode: '777'

    - name: Modify ownership & permissions of the shared directory
      file:
        path: /mnt/pve/hdd-sda/nfs-shares/k8s-pvs
        owner: nobody
        group: nogroup
        mode: '777'

    - name: Add the directory to the NFS configuration file
      lineinfile:
        path: /etc/exports
        line: '/mnt/pve/hdd-sda/nfs-shares/k8s-pvs *(rw,sync,no_subtree_check,no_root_squash)'

    - name: Export the shared directory 
      command:
        cmd: exportfs -a 

    - name: Restart NFS service
      command:
        cmd: systemctl restart nfs-kernel-server


